### ISSUE TITLE
Feature: Provide physical layer of CAN-interface

### ISSUE THREAD

**Issue by iiskumari** [Fraunhofer-IIS/ogre#10]

**Comment by moverbeck-iis** [comment]
The present release already supports the CAN-Interface. It is tested with a standard USB-CAN-Adapter (Lawicel CANUSB Adapter) and PC.
The connection is available and data can be sent and received.

**Comment by cstrobel-iis** [comment]
The usage of the CAN interface is described here:
https://github.com/Fraunhofer-IIS/ogre/wiki/CAN-interface
