### ISSUE TITLE
Feature: GSM-Modul

### ISSUE THREAD

**Issue by iiskumari** [Fraunhofer-IIS/ogre#11]
The firmware under development already supports the LTE-Modul Huawei K5150 and the Telit GC864-QUAD V2 (2nd not fully tested at present)  as well as PPP connections.
This will be available with the next release of OGRE.

**Comment by moverbeck-iis** [comment]
The broadband communication moduls can be used (see https://github.com/Fraunhofer-IIS/ogre/wiki/Validated-mobile-broadband-devices). Ticket is closed.
