### ISSUE TITLE
Nable PPS for non-root user

### ISSUE THREAD

**Issue by zyxbac** [Fraunhofer-IIS/ogre#15]
Use of /dev/pps0 as non-root user requieres 
sudo chmod a+rw /dev/pps0
after each reboot. 

Make this default by udev rule?

**Comment by moverbeck-iis** [comment]
Hi zyxbac,
we discussed your wish internal and found a fast fix:
Could you check if the following procedure works for you?
Execute the following command as root user:
 
crontab –e

Add the following line:

@reboot  chmod a+rw /dev/pps0

Best regards
Matthias

**Comment by ThyMYthOS** [comment]
Better use a UDEV rule if possible.

**Comment by zyxbac** [comment]
I think ThyMYthOS is right, UDEV is better choice.

So what I did (and hope you will adopt for new goose images):

created new file /etc/udev/rules.d/pps.rules with the contents

`KERNEL=="pps[0-9]*", OWNER="root", GROUP="root", MODE="0666"`

works great. :)

**Comment by moverbeck-iis** [comment]
Thank you for the code. Yes, we will consider your proposal for next image.
Can we close the issue?

**Comment by zyxbac** [comment]
Personally I prefer closing the issue when a patch is committed or in this case, a new system image with any working fix is made available. At the end it depends how you like to manage this issue tracker.

**Comment by zyxbac** [comment]
Rethinking my suggested patch, it might be a cleaner solution adding a 'pps' group to the system and setting the rights 0660.

**Comment by cstrobel-iis** [comment]
Fixed in release v1.17.0
