### ISSUE TITLE
Signal Type not defined in OGRP schema

### ISSUE THREAD

**Issue by zyxbac** [Fraunhofer-IIS/ogre#16]
ogre_console 1.10.1 sends measurements with "signal_type":"E1B" which is not defined in ogrp schema 1.2 (see below)

"signal_type": {"enum": ["L1CA", "L2CA", "L2P_codeless", "L2CM", "L5I", "L5Q", "E5aI", "P1", "P2", "P5", "E1", "E5", "E6", "E5a", "E5b"]},

**Comment by cstrobel-iis** [comment]
The additional signal are now defined in the OGRP shema:
https://github.com/Fraunhofer-IIS/ogrp/commit/3d3dc73091c545355ef28b4187fe0ff16fa632d0
