### ISSUE TITLE
Feature: I want E5 AltBoc signal benefits

### ISSUE THREAD

**Issue by iiskumari** [Fraunhofer-IIS/ogre#8]
## Description

Planned to be availble in september 2016.

**Comment by moverbeck-iis** [comment]
Tracking is available in working copy. Ranges have to be implemented. Integration in ogre is planned for end of July 2017.

**Comment by moverbeck-iis** [comment]
E5AltBOC is available since 1.13.1. Carrier has been fixed in latest release 1.16.1. So this issue can be closed!
