### ISSUE TITLE
Feature: Connection to radio-modem

### ISSUE THREAD

**Issue by iiskumari** [Fraunhofer-IIS/ogre#9]

**Comment by moverbeck-iis** [comment]
It is foreseen that a radio module is connected to the platform via serial RS232-interface.
The interface is already available and tested. The function test with the radio module is still pending.

**Comment by moverbeck-iis** [comment]
The description can be found under https://github.com/Fraunhofer-IIS/ogre/wiki/Serial-connection-on-the-embedded-board. Ticket is closed
